### ISSUE TITLE
Add Graph API domain note to README

### ISSUE THREAD

**Issue by markthiessen** [juunas11/aspnetcore2aadauth#1]
I kept running into permission denied remote errors when authenticating.

I discovered that initially the sample didn't work for me until I changed the config setting `OpenIdConnect:Resource` to `https://graph.windows.net`.

So, it seems that in my Azure AD I had permission to Azure AD graph, but not Microsoft Graph.

In order to use the setting `https://graph.microsoft.com`, I needed to add additional permissions to my app registration to access Microsoft Graph. After adding permisisons, the sample works.

It might be worth adding some notes there around required permissions as I spent some time debugging this.. I expect others will as well.

**Comment by juunas11** [comment]
Will do! Sorry for the late reply :)
