### ISSUE TITLE
Bad Request on /signin-oidc

### ISSUE THREAD

**Issue by aredfox** [juunas11/aspnetcore2aadauth#2]
All works well, until I try to login `login.microsoftonline.com` tries to redirect to.. Then I get the following error. Have I forgotten something, did I do something wrong?

```
Additional technical information:
--
Correlation ID: 523d3ab5-6970-4e53-9b40-2ebd2a7eab84
Timestamp: 2017-11-02 13:39:57Z
AADSTS50011: The reply address 'http://localhost:5000/signin-oidc' does not match the reply addresses configured for the application: 'afeb7fdb-48d5-48fd-a7be-d3eab0472dc7'. More details: not specified
```

**Comment by juunas11** [comment]
That means you have not configured the reply URL in Azure AD. Check the reply URLs there for your app.
