### ISSUE TITLE
SecurityTokenSignatureKeyNotFoundException

### ISSUE THREAD

**Issue by AlexJH4U** [juunas11/aspnetcore2aadauth#3]
@juunas11 
This doesn't work.

Currently, the configuration isn't binding, as line 48 of Startup.cs is commented out.  I'm assuming this was in error.

After that's corrected, I'm still having problems with signature validation.

`SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid':`

Thoughts?

**Comment by AlexJH4U** [comment]
I do believe it needs uncommented... but as for the other issue, a User Secret needs added with the ClientSecret.  I didn't see this in the quick start guide.

Hope this helps!

**Comment by AlexJH4U** [comment]
I have found out that App Registrations should be performed using the new Microsoft App Registration page in order to use the v2.0 endpoint.  Before doing this, my client secrets were never accepted.  You cannot simply use the Azure Portal to register your enterprise application, as usual and you can't use existing applications... you must register a new app using the link below:

https://apps.dev.microsoft.com/?deeplink=/appList

making things further complicated, you can't easily select what directory the app should be added to.  It will be added to your Microsoft account's originating directory.  If you're trying to create it for another directory, you'll have to log on to a Global Administrator directory user on the domain first.  (Which poses a problem, as I was previously added as a guest user to the directory, as it is for B2B purposes).

Hope this helps someone.  After using the new app registration page, and generating a secret in the page, and updating the code provided in this project to bind the correct ClientId and ClientSecret, it worked without a hitch.

**Comment by juunas11** [comment]
Right, in order to use the v2.0 endpoints, you must register in the other portal. If you define the app in Azure Portal, you must use v1 endpoints.
