### ISSUE TITLE
Failed to acquire token silently

### ISSUE THREAD

**Issue by cvabanuk3** [juunas11/aspnetcore2aadauth#9]
I have a created a MVC web app and intergrated with AAD as it was suggested. For the first time login and Authorize with AAD, I am able to get Token from the resource using AcquireTokenSilentAsync.
Once after the call, in the second rquest, always I am getting below error.
While debugging found that "OnAuthorizationCodeReceived" was not triggering upon second Authorization and no keyvalue was added to Cache at the same time the earlier cache also found empty.
I am not sure what I missed. 
Can you please let me know, how I can come out of this.

'Failed to acquire token silently as no token was found in the cache. Call method AcquireToken'

**Comment by juunas11** [comment]
OnAuthorizationCodeReceived is only triggered once. When the user is redirected back from AAD. The issue you have seems to be related to the token cache. Did you restart the app by chance? The default token cache is in-memory so will be reset if the process is killed.

**Comment by cvabanuk3** [comment]
Yes, you are right, issue exactly with TokenCache only. At every time when the controllers constructor executing, I am able to check no Cache tokens available.  That is why, my intention is to force login using exception filter in your code. But that one also not triggering.

**Comment by juunas11** [comment]
Hmm, but if you have the AdalSilentTokenAcquisitionException being thrown shouldn't it be caught? Are you sure you have registered the exception filter correctly?

**Comment by cvabanuk3** [comment]
Yes, I just followed you code.
services.AddMvc(opts =>
            {
                opts.Filters.Add(typeof(AdalTokenAcquisitionExceptionFilter));
            });

**Comment by juunas11** [comment]
Well, that's weird. Do you have the complete code up somewhere?

**Comment by cvabanuk3** [comment]
Please find the StartUp class :

public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            //JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(opts =>
            {
                opts.Filters.Add(typeof(AdalTokenAcquisitionExceptionFilter));
            });

            services.AddDataProtection();
            //services.AddDistributedMemoryCache();
            services.AddSession();
            services.Configure<FormOptions>(options =>
            {
                options.MultipartBodyLengthLimit = 300_000_000;
            });
            //services.AddCors();
            services.Configure<AuthValues>(Configuration.GetSection("Authentication"));

            services.AddSingleton<ITokenCacheFactory, TokenCacheFactory>();

            services.AddAuthentication(auth =>
            {
                auth.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddCookie()
            .AddOpenIdConnect(opts =>
            {
                Configuration.GetSection("Authentication").Bind(opts);
                //opts.RequireHttpsMetadata = false;

                opts.Events = new OpenIdConnectEvents
                {
                    OnAuthorizationCodeReceived = async ctx =>
                    {
                        HttpRequest request = ctx.HttpContext.Request;
                        //We need to also specify the redirect URL used
                        string currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, request.Path);
                        //Credentials for app itself
                        var credential = new ClientCredential(ctx.Options.ClientId, ctx.Options.ClientSecret);

                        //Construct token cache
                        ITokenCacheFactory cacheFactory = ctx.HttpContext.RequestServices.GetRequiredService<ITokenCacheFactory>();
                        TokenCache cache = cacheFactory.CreateForUser(ctx.Principal);

                        var authContext = new AuthenticationContext(ctx.Options.Authority, cache);

                        string resource = "https://azurecmstestdomain.onmicrosoft.com/azurecms";
                        AuthenticationResult result = await authContext.AcquireTokenByAuthorizationCodeAsync(
                            ctx.ProtocolMessage.Code, new Uri(currentUri), credential, resource);

                        ctx.HandleCodeRedemption(result.AccessToken,result.IdToken);
                    }
                };
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                //app.UseExceptionHandler("/Home/Error");
                //Outside dev, require HTTPS and use HSTS
                app.Use(async (ctx, next) =>
                {
                    if (!ctx.Request.IsHttps)
                    {
                        //Insecure request, redirect to HTTPS side
                        HttpRequest req = ctx.Request;
                        string url = "https://" + req.Host + req.Path + req.QueryString;
                        ctx.Response.Redirect(url, permanent: true);
                    }
                    else
                    {
                        //Apply Strict Transport Security to all secure requests
                        //All requests done over secure channel for next year
                        ctx.Response.Headers["Strict-Transport-Security"] = "max-age=31536000";

                        await next();
                    }
                });
            }
            //app.UseCors(builder => builder.WithOrigins("https://login.microsoftonline.com"));

            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvcWithDefaultRoute();
            //app.UseMvc(routes =>
            //{
            //    routes.MapRoute(
            //        name: "default",
            //        template: "{controller=Home}/{action=Index}/{id?}");
            //});

        }
    }

Token logic :

private async Task GetAccessTokenAsync()
        {
            string authority = _authOptions.Authority;

            var cache = _tokenCacheFactory.CreateForUser(User);

            var authContext = new AuthenticationContext(authority, cache);

            //App's credentials may be needed if access tokens need to be refreshed with a refresh token
            string clientId = _authOptions.ClientId;
            string clientSecret = _authOptions.ClientSecret;
            var credential = new ClientCredential(clientId, clientSecret);
            var userId = User.GetObjectId();
            //var userName = User.GetUserName();
            string resourceString = "https://azurecmstestdomain.onmicrosoft.com/azurecms";

            AuthenticationResult result = null;
                result = await authContext.AcquireTokenSilentAsync( resourceString,  credential,
                    new UserIdentifier(userId, UserIdentifierType.UniqueId));
                bearerToken = result.AccessToken;
         
        }

**Comment by cvabanuk3** [comment]
I don't think it is my code :)

**Comment by juunas11** [comment]
Could you also show the code in the controller where you are trying to get the access token?

**Comment by cvabanuk3** [comment]
namespace JsonParser.Controllers
{
     [Authorize]    
    public class HomeController : Controller
    {

        #region evaluating sarted

        private readonly IHostingEnvironment _hostingEnvironment;
        internal readonly ITokenCacheFactory _tokenCacheFactory;
        internal readonly AuthValues _authOptions;
        private bool isProd = false;
        private string bearerToken = string.Empty;

        public HomeController(IHostingEnvironment hostingEnvironment, ITokenCacheFactory tokenCacheFactory, IOptions<AuthValues> authOptions)
        {
            _hostingEnvironment = hostingEnvironment;
            _tokenCacheFactory = tokenCacheFactory;
            _authOptions = authOptions.Value;

              CleanUpTempFiles();
        }

        public IActionResult Index() => View();

        [HttpPost]
        public async Task<JsonResult> GetStoryDetails(string storyId)
        {
            int a = 0;
            if (storyId == null)
                return Json(new { error = "No input received" });

            var document = await GetDocumentString(storyId);

            if (document == null)
                return Json(new { error = "No document found" });
            
            var storyObject = JsonConvert.DeserializeObject<dynamic>(document);

            if (storyObject == null || storyObject.Count ==0)
                return Json(new { error = "Document serialization failed" });

            ResponseObject sr = new ResponseObject();

            string title = string.Empty;
            if (((JArray)storyObject)[0] != null && ((JArray)storyObject)[0]["title"] != null)
                title = ((JArray)storyObject)[0]["title"].ToString();

            string localesHtml = string.Empty;
            string Html = TreeViewHelper.GetHtml(((JArray)storyObject)[0], storyId);
            string VideoId = GetVideoId(storyObject);
            string imageSrc = await GetImageSource(storyObject);

            return Json(new { videoId = VideoId, ImageSrc = imageSrc, html = Html });
        }

        /// <summary>
        /// Create/Upload an Image
        /// </summary>
        [HttpPost]
        [RequestSizeLimit(2147483647)]
        public async Task<ActionResult> CheckForDuplicates(RequestContext rc)
        {
            bool isDuplicatesFound = false;

            rc.RequestId = Guid.NewGuid().ToString();
            string logFile = CreateLogFile(rc.RequestId + ".txt");
            var files = Request.Form.Files;

            List<Image> lstSelectedImages = new List<Image>();
            var lstDuplicateImages = new List<Image>();

            Logger.Log(logFile, "Started Processing files");

            Dictionary<string, Dictionary<string, IFormFile>> inputFiles = ProcessFileLocales(Request.Form.Files);

            Logger.Log(logFile, "Compleated Processing files, Objects requested : ");


            bool isSaved = false;
            isSaved = await SaveToTemp(rc.RequestId, inputFiles);

            Logger.Log(logFile, "Started Checking for Duplicates");

            foreach (var file in inputFiles)
            {
                string imageName = file.Key;
                Logger.Log(logFile, "=================================");

                var image = new Image();

                image.name = file.Key;

                if ((file.Value).Count <= 0)
                {
                    image.localizationInfo = "No localized images found in selected folder";
                    Logger.Log(logFile, "skipping process, No localized images found for Image : " + file.Key);
                    Logger.Log(logFile, "=================================");
                    lstSelectedImages.Add(image);
                    continue;
                }

                string sourceImageName = file.Key;

                ResponseObject resObj;

                JToken sourceImageFileMDFToken = null;

                Logger.Log(logFile, "Identifying en-us Localized Image Metadata File for " + file.Key);

                resObj = await GetenusDocumentJsonByName(sourceImageName, DocType.locImageMDF);

                if (!resObj.isSuccess)
                {
                    Logger.Log(logFile, "skipping process, No localized image metadata file found for Image : " + file.Key);
                    LogError(logFile, resObj);
                    Logger.Log(logFile, "=================================");
                    lstSelectedImages.Add(image);
                    continue;
                }
                if (resObj.jsonResult.Count() <= 0)
                {
                    image.localizationInfo = "No localized image metadat file found for image : " + file.Key;
                    lstSelectedImages.Add(image);
                    continue;
                }

                image.duplicateImages = lstDuplicateImages;
                lstSelectedImages.Add(image);
            }

            rc.selectedImages = lstSelectedImages;

            Logger.Log(logFile, "Compleated Checking for Duplicates");

            if (isDuplicatesFound)
                return View(rc);
            else
                return RedirectToAction("LocalizeAllImages", rc);
        }

       #endregion evaluation end

        #region private methods

        private async Task GetAccessTokenAsync()
        {
            string authority = _authOptions.Authority;

            var cache = _tokenCacheFactory.CreateForUser(User);

            var authContext = new AuthenticationContext(authority, cache);

            //App's credentials may be needed if access tokens need to be refreshed with a refresh token
            string clientId = _authOptions.ClientId;
            string clientSecret = _authOptions.ClientSecret;
            var credential = new ClientCredential(clientId, clientSecret);
            var userId = User.GetObjectId();
            //var userName = User.GetUserName();
            string resourceString = "https://azurecmstestdomain.onmicrosoft.com/azurecms";
            if (isProd)
            {
                resourceString = "";
            }

            AuthenticationResult result = null;
          
                result = await authContext.AcquireTokenSilentAsync(
                    resourceString,
                    credential,
                    new UserIdentifier(userId, UserIdentifierType.UniqueId));                

                bearerToken = result.AccessToken;           
           
        }     

		private async Task<ResponseObject> GetenusDocumentJsonByName(string sourceImageName, string docType)
        {
            ResponseObject result = null;

            string filter = "'$type'eq'" + docType + "'and'_name'eq'" + sourceImageName + "'and'_locale'eq'en-us'";
            CMSContext context = new GetDocument(filter, isProd);

            if (string.IsNullOrEmpty(bearerToken))
                await GetAccessTokenAsync();

            result = await HttpHelper.GetJsonAsync(context, bearerToken);
            return result;
        }		

    }
}

**Comment by juunas11** [comment]
Well, looking at it, the exception filter should trigger. The exception should be thrown out of the action method and then it should cause a re-authentication.

**Comment by cvabanuk3** [comment]
Yes, but it is not happening. I am not getting where/what I missed.

**Comment by cvabanuk3** [comment]
Hi, I just moved call to GetAccessToken to the first line in the Action method and found invoking re-authentication. It is good to see but this is causing to redirect to current Action method rather than landing page.

**Comment by cvabanuk3** [comment]
Thanks for your quick response @juunas11 , I am able to resolve the Token issue. Thanks for the Article and support.
